# Generated by Django 4.0.5 on 2022-06-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slogan', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('1', 'baked good'), ('2', 'dairy'), ('3', 'fruit'), ('4', 'meat'), ('5', 'seafood'), ('6', 'vegetable')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('1', 'baked good'), ('2', 'dairy'), ('3', 'fruit'), ('4', 'meat'), ('5', 'seafood'), ('6', 'vegetable')], max_length=255)),
            ],
        ),
    ]
