# Generated by Django 4.0.5 on 2022-06-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food4CheapProj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='carbohydrates',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='measurement',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='serving_size',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
