# Generated by Django 4.0.5 on 2022-06-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food4CheapProj', '0002_product_calories_product_carbohydrates_product_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
