# Generated by Django 4.0.5 on 2022-07-07 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Food4CheapProj', '0004_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='purchaser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
